version: 0.0
os: linux
files:
  - source: webapp.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: /opt/tomcat/bin/shutdown.sh
 
  AfterInstall:
    - location: /opt/tomcat/bin/startup.sh
      timeout: 300
      runas: root
